bind_addr = ":8080"
log_level = "debug"
cors_origin = "http://localhost:7082"

[store]
database_url = "host=localhost dbname=db_technology_stack_000000_dev user=userexample password=passwordexample sslmode=disable"
